#!/usr/bin/env python3
"""Tests for knowledge_manager.py — KnowledgeManager class."""

import json
import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "scripts"))

from _builder.knowledge_manager import KnowledgeManager


class TestKnowledgeExtractFromDocs(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self.docdir = tempfile.mkdtemp()
        self.mgr = KnowledgeManager(self.tmpdir)

    def tearDown(self):
        import shutil
        shutil.rmtree(self.tmpdir, ignore_errors=True)
        shutil.rmtree(self.docdir, ignore_errors=True)

    def test_readme_extraction(self):
        readme = os.path.join(self.docdir, "README.md")
        with open(readme, "w") as f:
            f.write("# Test Project\nA test project for knowledge extraction.")

        knowledge = self.mgr.extract_from_docs([readme])
        self.assertIn("Test Project", knowledge["architecture"])

    def test_design_doc(self):
        design = os.path.join(self.docdir, "DESIGN.md")
        with open(design, "w") as f:
            f.write("# Architecture Overview\nThe system uses microservices.")

        knowledge = self.mgr.extract_from_docs([design])
        self.assertIn("microservices", knowledge["architecture"])

    def test_contributing_doc(self):
        contrib = os.path.join(self.docdir, "CONTRIBUTING.md")
        with open(contrib, "w") as f:
            f.write("# Contributing\nAll PRs must pass CI.")

        knowledge = self.mgr.extract_from_docs([contrib])
        self.assertIn("must pass CI", knowledge["constraints"])

    def test_empty_doc_list(self):
        knowledge = self.mgr.extract_from_docs([])
        self.assertEqual(knowledge["architecture"], "")

    def test_nonexistent_file(self):
        knowledge = self.mgr.extract_from_docs(["/nonexistent/file.md"])
        self.assertEqual(knowledge["architecture"], "")


class TestKnowledgeWriteFiles(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self.mgr = KnowledgeManager(self.tmpdir)

    def tearDown(self):
        import shutil
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_write_architecture(self):
        knowledge = {"architecture": "# Architecture\nTest arch"}
        self.mgr.write_knowledge_files(knowledge)
        arch_path = os.path.join(self.mgr.knowledge_dir, "architecture.md")
        self.assertTrue(os.path.exists(arch_path))

    def test_write_module(self):
        # Per-module files are no longer auto-generated by write_knowledge_files.
        # Modules are stored as part of architecture/constraints, not as separate files.
        # Test that architecture content is written correctly instead.
        knowledge = {"architecture": "# Architecture\n## Modules\nlib_bdev module"}
        self.mgr.write_knowledge_files(knowledge)
        arch_path = os.path.join(self.mgr.knowledge_dir, "architecture.md")
        self.assertTrue(os.path.exists(arch_path))

    def test_write_glossary(self):
        knowledge = {"glossary": "# Glossary\n- **API_entry**: External API"}
        self.mgr.write_knowledge_files(knowledge)
        gloss_path = os.path.join(self.mgr.knowledge_dir, "glossary.md")
        self.assertTrue(os.path.exists(gloss_path))

    def test_skip_empty_sections(self):
        knowledge = {"architecture": "", "glossary": "# Glossary\nTest"}
        self.mgr.write_knowledge_files(knowledge)
        arch_path = os.path.join(self.mgr.knowledge_dir, "architecture.md")
        self.assertFalse(os.path.exists(arch_path))
        gloss_path = os.path.join(self.mgr.knowledge_dir, "glossary.md")
        self.assertTrue(os.path.exists(gloss_path))


class TestKnowledgeIndex(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self.mgr = KnowledgeManager(self.tmpdir)
        # Create some test knowledge files
        knowledge = {
            "architecture": "# Architecture\n## Overview\nTest\n## Components\nA, B",
            "glossary": "# Glossary\n- **API**: Application Programming Interface",
        }
        self.mgr.write_knowledge_files(knowledge)

    def tearDown(self):
        import shutil
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_build_index(self):
        index = self.mgr.build_index()
        self.assertIn("files", index)
        self.assertIn("topics", index)
        self.assertGreater(len(index["files"]), 0)

    def test_index_has_headings(self):
        index = self.mgr.build_index()
        # Architecture should have "Overview" and "Components" headings
        arch_file = next(f for f in index["files"] if f["name"] == "architecture.md")
        self.assertIn("Overview", arch_file["headings"])
        self.assertIn("Components", arch_file["headings"])


class TestKnowledgePack(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self.mgr = KnowledgeManager(self.tmpdir)
        knowledge = {
            "architecture": "# Architecture\n## Overview\nTest project\n## Components\nA, B",
            "glossary": "# Glossary\n- **API**: Application Programming Interface",
        }
        self.mgr.write_knowledge_files(knowledge)

    def tearDown(self):
        import shutil
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_lite_pack(self):
        pack = self.mgr.generate_pack("lite")
        self.assertIn("files", pack)
        self.assertIn("topics", pack)
        self.assertIn("architecture_summary", pack)
        # Check file written
        pack_path = os.path.join(self.tmpdir, ".knowledge_pack_lite.json")
        self.assertTrue(os.path.exists(pack_path))

    def test_standard_pack(self):
        pack = self.mgr.generate_pack("standard")
        self.assertIn("architecture", pack)
        self.assertIn("glossary", pack)
        # Standard pack should contain more detail than lite
        self.assertIn("files", pack)


class TestKnowledgeQuery(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self.mgr = KnowledgeManager(self.tmpdir)
        knowledge = {
            "architecture": "# Architecture\n## Overview\nSPDK block device layer uses bdev modules",
            "glossary": "# Glossary\n- **bdev**: Block device abstraction in SPDK",
        }
        self.mgr.write_knowledge_files(knowledge)

    def tearDown(self):
        import shutil
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_query_found(self):
        result = self.mgr.query_knowledge("bdev")
        self.assertIn("bdev", result.lower())

    def test_query_not_found(self):
        result = self.mgr.query_knowledge("nonexistent_topic_xyz")
        self.assertIn("No knowledge found", result)

    def test_query_multi_file(self):
        result = self.mgr.query_knowledge("SPDK")
        # Should find content from both architecture and glossary
        self.assertIn("SPDK", result)


class TestDiscoverDocFiles(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self.sourcedir = tempfile.mkdtemp()
        self.mgr = KnowledgeManager(self.tmpdir)
        # Create some doc files
        with open(os.path.join(self.sourcedir, "README.md"), "w") as f:
            f.write("# Test")
        os.makedirs(os.path.join(self.sourcedir, "docs"))
        with open(os.path.join(self.sourcedir, "docs", "design.md"), "w") as f:
            f.write("# Design")
        # Create non-doc file
        with open(os.path.join(self.sourcedir, "main.c"), "w") as f:
            f.write("int main() {}")

    def tearDown(self):
        import shutil
        shutil.rmtree(self.tmpdir, ignore_errors=True)
        shutil.rmtree(self.sourcedir, ignore_errors=True)

    def test_discovers_docs(self):
        docs = self.mgr._discover_doc_files(self.sourcedir)
        names = [os.path.basename(d) for d in docs]
        self.assertIn("README.md", names)
        self.assertIn("design.md", names)

    def test_skips_source_files(self):
        docs = self.mgr._discover_doc_files(self.sourcedir)
        names = [os.path.basename(d) for d in docs]
        self.assertNotIn("main.c", names)


if __name__ == "__main__":
    unittest.main()
